// флаг столкновений для каждого объекта
export const COLLISION_FLAG = {
	playerShip: 1,
	playerShipFire: 2,
	enemyShip: 4,
	enemyShipFire: 8,
	asteroid: 16,
	bonus: 32,
	bossEnemy: 64,
	bossEnemyFireBoss: 128,
};
// флаги взаимных столкновений объектов
export const MUTUAL_COLLISION_FLAG = {
	playerShip: 116,
	playerShipFire: 84,
	enemyShip: 0,
	enemyShipFire: 1,
	asteroid: 16,
	bonus: 0,
	bossEnemy: 0,
	bossEnemyFireBoss: 1,
};

// ресурсы игры (изображения, звуки, музыка)
export const GAME_ASSETS = {
	enemyShips: 3,
	enemyBosses: 2,
	sprites: {
		playerShip: {
			url: "./src/assets/sprites/space_ship_player.png",
			width: 80,
			height: 80,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			spriteFire: "playerShipFire",
			explosion: "explosionShip",
		},
		playerShipFire: {
			url: "./src/assets/sprites/laser_shot_player.png",
			width: 10,
			height: 84,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			explosion: "playerLaserDestroyed",
			times: 1,
		},
		playerLaserDestroyed: {
			url: "./src/assets/sprites/sparks_blue.png",
			width: 64,
			height: 64,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: true,
			speedAnimation: 10,
			firstFrame: 0,
			lastFrame: 19,
			startFrame: 0,
		},
		enemyShip1: {
			url: "./src/assets/sprites/enemy_spaceship1.png",
			width: 80,
			height: 63,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			spriteFire: "enemyShipFire1",
			explosion: "explosionShip",
		},
		enemyShipFire1: {
			url: "./src/assets/sprites/fire_shot_enemy1.png",
			width: 10,
			height: 84,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			explosion: "enemyLaserDestroyed",
			times: 1,
		},
		enemyLaserDestroyed: {
			url: "./src/assets/sprites/sparks_red.png",
			width: 64,
			height: 64,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: true,
			speedAnimation: 10,
			firstFrame: 0,
			lastFrame: 19,
			startFrame: 0,
		},
		enemyShip2: {
			url: "./src/assets/sprites/enemy_spaceship2.png",
			width: 70,
			height: 64,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			spriteFire: "enemyShipFire2",
			explosion: "explosionShip",
		},
		enemyShipFire2: {
			url: "./src/assets/sprites/fire_shot_enemy2.png",
			width: 38,
			height: 38,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			explosion: "enemyLaserDestroyed",
			times: 1,
		},
		enemyFireDestroyed2: {
			url: "./src/assets/sprites/sparks_red.png",
			width: 64,
			height: 64,
			animate: true,
		},
		enemyShip3: {
			url: "./src/assets/sprites/enemy_spaceship3.png",
			width: 70,
			height: 64,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			spriteFire: "enemyShipFire3",
			explosion: "explosionShip",
		},
		enemyShipFire3: {
			url: "./src/assets/sprites/fire_shot_enemy3.png",
			width: 38,
			height: 20,
			offsetX: 0,
			offsetY: 0,
			animate: false,
			explosion: "enemyLaserDestroyed",
			times: 2,
		},
		enemyFireDestroyed3: {
			url: "./src/assets/sprites/sparks_red.png",
			width: 64,
			height: 64,
			animate: true,
		},
		bossEnemy1: {
			url: "./src/assets/sprites/boss_enemy1.png",
			width: 128,
			height: 184,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 256,
			offsetHeight: 368,
			animate: true,
			once: false,
			speedAnimation: 240,
			firstFrame: 0,
			lastFrame: 13,
			startFrame: 0,
			spriteFire: "bossEnemyFire1",
			explosion: "explosionShip",
		},
		bossEnemyFire1: {
			url: "./src/assets/sprites/boss_fire1.png",
			width: 80,
			height: 80,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: false,
			speedAnimation: 30,
			firstFrame: 0,
			lastFrame: 23,
			startFrame: 0,
			explosion: "enemyFireDestroyed3",
			count: 3,
		},
		bossEnemy2: {
			url: "./src/assets/sprites/boss_enemy2.png",
			width: 128,
			height: 148,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 256,
			offsetHeight: 296,
			animate: true,
			once: false,
			speedAnimation: 240,
			firstFrame: 0,
			lastFrame: 7,
			startFrame: 0,
			spriteFire: "bossEnemyFire2",
			explosion: "explosionShip",
		},
		bossEnemyFire2: {
			url: "./src/assets/sprites/boss_fire2.png",
			width: 64,
			height: 16,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 256,
			offsetHeight: 64,
			animate: true,
			once: false,
			speedAnimation: 30,
			firstFrame: 0,
			lastFrame: 7,
			startFrame: 0,
			explosion: "enemyFireDestroyed3",
			count: 3,
		},
		asteroid1: {
			url: "./src/assets/sprites/asteroids-rotate_1.png",
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: false,
		},
		asteroid2: {
			url: "./src/assets/sprites/asteroids-rotate_2.png",
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: false,
		},

		explosionAsteroid: {
			url: "./src/assets/sprites/explosion_Asteroid.png",
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 256,
			offsetHeight: 256,
			animate: true,
			once: true,
			speedAnimation: 10,
			firstFrame: 0,
			lastFrame: 31,
			startFrame: 0,
		},

		explosionShip: {
			url: "./src/assets/sprites/explosion_ship.png",
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 192,
			offsetHeight: 192,
			animate: true,
			once: true,
			speedAnimation: 30,
			firstFrame: 0,
			lastFrame: 19,
			startFrame: 0,
		},

		coin: {
			url: "./src/assets/sprites/coin.png",
			width: 32,
			height: 32,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: false,
			speedAnimation: 30,
			firstFrame: 0,
			lastFrame: 5,
			startFrame: 0,
		},
		heart: {
			url: "./src/assets/sprites/heart.png",
			width: 32,
			height: 32,
			offsetX: 0,
			offsetY: 0,
			offsetWidth: 128,
			offsetHeight: 128,
			animate: true,
			once: false,
			speedAnimation: 30,
			firstFrame: 0,
			lastFrame: 5,
			startFrame: 0,
		},
		gameover: {
			url: "./src/assets/sprites/gameover.png",
			width: 250,
			height: 112,
			offsetX: 0,
			offsetY: 0,
			animate: false,
		},
	},

	backgrounds: {
		space1: "./src/assets/sprites/space1.png",
		space2: "./src/assets/sprites/space2.png",
		space3: "./src/assets/sprites/space3.png",
		space4: "./src/assets/sprites/space4.png",
		space5: "./src/assets/sprites/space5.png",
	},

	audioEffects: {
		explosionShip: "./src/assets/audio/explosion_1.mp3",
		playerShipFire: "./src/assets/audio/laser_shot_1.mp3",
		coin: "./src/assets/audio/coin.mp3",
		heart: "./src/assets/audio/heart.mp3",
	},

	music: {
		music1: "./src/assets/music/Alone_Against_Enemy.ogg",
		music2: "./src/assets/music/Battle_in_the_Stars.ogg",
		music3: "./src/assets/music/Space_Heroes.ogg",
		music4: "./src/assets/music/Without_Fear.ogg",
		boss: "./src/assets/music/DeathMatch.ogg",
		gameover: "./src/assets/music/Defeated_gameover.ogg",
		victory: "./src/assets/music/Victory.ogg",
	},
}

// паттерны движений противника
export const MOVEMENT = {
	patterns: 8,
	increaseSpeed: 0.2,
	increaseEnemys: 4,
	1: {
		enemyStart: 2,
		enemyMax: 8,
		posY: 120,
		posX: 100,
		speedX: 2,
		speedY: 0,
		pattern: "backAndForthMovement",
	},
	2: {
		enemyStart: 8,
		enemyMax: 16,
		posX: 100,
		posY: 50,
		speedX: 2,
		speedY: 0,
		deviationX: 150,
		deviationY: 100,
		deviationSpeedY: 3,
		pattern: "clockwiseMovement",
	},
	3: {
		enemyStart: 3,
		enemyMax: 12,
		posY: 100,
		posX: 100,
		speedX: 3,
		speedY: 0,
		pattern: "backAndForthMovement",
	},
	4: {
		enemyStart: 8,
		enemyMax: 16,
		posX: 100,
		posY: 50,
		speedX: -2,
		speedY: 0,
		deviationX: 150,
		deviationY: 100,
		deviationSpeedY: 3,
		pattern: "counterclockwiseMovement",
	},
	5: {
		enemyStart: 4,
		enemyMax: 16,
		posY: 80,
		posX: 100,
		speedX: 4,
		speedY: 0,
		pattern: "backAndForthMovement",
	},
	6: {
		enemyStart: 8,
		enemyMax: 16,
		posX: 0,
		posY: 180,
		speedX: -2,
		speedY: -3,
		deviationX: 120,
		deviationY: 100,
		deviationSpeedY: 2,
		pattern: "figureEightMovement",
	},
	7: {
		enemyStart: 1,
		enemyMax: 1,
		posX: 0,
		posY: -150,
		speedX: 0,
		speedY: 3,
		deviationX: 50,
		deviationY: 400,
		deviationSpeedX: 2,
		deviationSpeedY: 2,
		pattern: "bossEnemyMovement",
	},
	8: {
		enemyStart: 8,
		enemyMax: 24,
		posX: 0,
		posY: -150,
		speedX: 3,
		speedY: 3,
		deviationX: 100,
		deviationY: 100,
		deviationSpeedX: 3,
		deviationSpeedY: 1.5,
		pattern: "randomEnemyMovement",
	},
};

// настройки игровых объектов
export const GAME_OPTIONS = {
	playerShip: {
		lives: 3,
		health: 10,
		damage: 4,
		maxLives: 7,
		incSpeedX: 0.2,
		incSpeedY: 0.2,
		maxSpeedX: 10,
		maxSpeedY: 10,
	},
	playerShipFire: {
		lives: 1,
		health: 1,
		damage: 1,
		speedX: 0,
		speedY: -15,
	},
	enemyShip: {
		lives: 1,
		health: 3,
		damage: 2,
		score: 5,
		bonusChance: 0.3,
		fireCnance: 0.005,
		incrementFireCnance: 0.0002,
	},
	enemyShipFire: {
		lives: 1,
		health: 1,
		damage: 1,
		speedX: 0,
		speedY: 12,
	},
	asteroid: {
		lives: 1,
		health: 1,
		damage: 1,
		score: 2,
	},
	coin: {
		lives: 1,
		health: 1,
		damage: 0,
		score: 10,
	},
	heart: {
		lives: 1,
		health: 1,
		damage: 0,
		score: 0,
		bonusLives: 1,
	},
	bossEnemy: {
		lives: 1,
		health: 50,
		damage: 10,
		score: 500,
		bonusChance: 1,
		fireCnance: 0.009,
		incrementFireCnance: 0.0005
	},
	bossEnemyFireBoss: {
		lives: 1,
		health: 1,
		damage: 5,
		speedX: 0,
		speedY: 5,
	},
	startPos: {
		enemyShip: {
			maxPosY: -100,
			minPosY: -200,
			minSpeedX: 0.5,
			maxSpeedX: 1,
			minSpeedY: 0.1,
			maxSpeedY: 0.5,
		},
		asteroid: {
			maxCount: 3,
			maxPosY: -20,
			minPosY: -100,
			minSpeedX: 0,
			maxSpeedX: 1,
			minSpeedY: 0.5,
			maxSpeedY: 2,
		},
	}
}